name: Locket
version: ${version}
author: Himmelt
main: org.soraworld.locket.Locket
website: https://github.com/Himmelt/Locket
description: Locket Plugin.
depend:
  - Violet
permissions:
  locket.admin:
    default: op
