name: Locket
version: ${version}
author: Himmelt
main: org.soraworld.locket.LocketPlugin
website: https://github.com/Himmelt/Locket
description: Locket Spigot Plugin.
api-version: '1.15'
depend:
  - Violet
permissions:
  locket.admin:
    default: op
