name: Locket
main: org.soraworld.locket.Locket
author: Himmelt
softdepend: [WorldGuard, Residence, Towny, Factions]
version: 1.7.10-0.0.3
description: Locket is a chest protection plugin for Bukkit.
commands:
   locket:
      permission: locket.command
      usage: |
         /lock
      aliases: [lock, locket]
permissions:
   locket.command:
      description: Command permission for Locket
      default: true
   locket.lock:
      description: Basic lock permission
      default: true
   locket.edit:
      description: Edit sign permission
      default: true